name: Lint Code

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Identify changed files
        id: changed-files
        run: |
          CHANGED_FILES="$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})"
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES"     >> $GITHUB_ENV
          echo "EOF"                >> $GITHUB_ENV


      - name: Lint Dockerfiles
        run: |
          CLEANED=$(echo "$CHANGED_FILES" | tr -d '\r')
          for file in $CLEANED; do
            if [[ -f "$file" && "$(basename "$file")" == "Dockerfile" ]]; then
              echo "Linting $file"
              cat "$file" | docker run --rm -i hadolint/hadolint
            fi
          done

      - name: Lint Shell scripts
        run: |
          CLEANED=$(echo "$CHANGED_FILES" | tr -d '\r')
          for file in $CLEANED; do
            if [[ "$file" == *.sh && -f "$file" ]]; then
              echo "Linting $file"
              docker run --rm -v "${{ github.workspace }}:/mnt" koalaman/shellcheck:stable "/mnt/$file"
            fi
          done

      - name: Install Python linters
        run: |
          pip install flake8 pylint

      - name: Lint Python scripts
        run: |
          CLEANED=$(echo "$CHANGED_FILES" | tr -d '\r')
          for file in $CLEANED; do
            echo "Potential Python file: $file"
            if [[ "$file" == *.py && -f "$file" ]]; then
              echo "Running flake8 for $file"
              flake8 "$file" --max-line-length=120

              echo "Running pylint for $file"
              pylint "$file" --max-line-length=120 --disable="C0103,C0114,C0115"
            fi
          done
